source 'https://rubygems.org'

gem 'sqlite3'
gem 'pg'
gem 'parslet', '1.6.2'
gem 'sinatra'
gem 'rest-client'
gem 'rack-timeout'
gem 'json'
gem 'haml'
gem 'rspec'
gem 'pry'
gem 're2', git: 'https://github.com/greensnark/re2.git'
gem 'gserver'
