source 'https://rubygems.org'

gem 'sqlite3'
gem 'dbi'
gem 'dbd-pg'
gem 'parslet'
gem 'sinatra'
gem 'rest-client'
gem 'rack-timeout'
gem 'json'
gem 'haml'
gem 'rspec'
gem 're2', git: 'https://github.com/greensnark/re2.git'
gem 'levenshtein-ffi'
