#! /usr/bin/env perl

use strict;
use warnings;

use Henzell::Config qw/%CONFIG @LOGS @MILESTONES/;
use Henzell::Utils;

sub fetch_file($) {
  my $file = shift;
  unless ($$file{url}) {
    print "Skipping $$file{path}, no URL\n";
    return;
  }
  print "Fetching $$file{url} -> $$file{path}\n";
  system(qq{wget -q -c $$file{url} -O $$file{path} >/dev/null 2>&1});
}

sub main() {
  Henzell::Utils::lock_or_exit();
  Henzell::Config::read();
  fetch_file($_) for (@LOGS, @MILESTONES);
}

main();
