#! /usr/bin/perl

use strict;
use warnings;

use lib 'lib';
use Henzell::FSLearnDB;
use Henzell::SQLLearnDB;

my $dbdir = shift() || 'dat/learndb';
my $file = shift() || 'dat/learn.db';

my $db = Henzell::SQLLearnDB->new($file)
  or die "Couldn't open LearnDB at $file: $!";

my $fs = Henzell::FSLearnDB->new($dbdir);
$db->disable_fsync();
$fs->each_term(
  sub {
    my $term = shift;
    my @definitions = $fs->definitions($term);
    if (@definitions) {
      $db->add($term, $_) for @definitions;
    }
  });

warn "Converted $dbdir to $file\n";
