#! /usr/bin/perl

use strict;
use warnings;

use Henzell::SQLLearnDB;

my $dbdir = shift() || 'dat/learndb';
my $file = shift() || 'dat/learn.db';

my $db = Henzell::SQLLearnDB->new($file)
  or die "Couldn't open LearnDB at $file: $!";

my $fs = Henzell::FSLearnDB->new($dbdir);
$fs->each_term(
  sub {
    my $term = shift;
    my @definitions = $fs->definitions($term);
    if (@definitions) {
      $fs->add($term, $_) for @definitions;
    }
  });

my $SCHEMA = <<SCHEMA;
CREATE TABLE terms (id INTEGER PRIMARY KEY AUTOINCREMENT,
                    term STRING);

CREATE TABLE definitions (id INTEGER PRIMARY KEY AUTOINCREMENT,
                          term
SCHEMA
