#! /bin/bash

set -e

GIT_URL=https://github.com/crawl/crawl.git
SOURCE_DIR=current

if [[ ! -d "$SOURCE_DIR" ]]; then
    git clone $GIT_URL $SOURCE_DIR
fi

cd $SOURCE_DIR
git pull
git submodule update --init

cd crawl-ref
# ctags incantations courtesy |amethyst
ctags -R \
    --langdef=crawlmap \
    --langmap=crawlmap:+.des \
    --regex-crawlmap='/^ *NAME: *([^ ]*)/\1/q,map,map definition/' \
    --regex-c++='/^ *DEF_BITFIELD *\( *([a-zA-Z0-9_:]*)/\1/t/' \
    -I decltype+ \
    --extra=+q \
    --exclude=contrib \
    --exclude=android-project \
    --exclude=saves \
    *

# And compile the binary for playable:*
cd source
make clean && make -j5 HURRY=y

if [[ -f crawl ]]; then
    mv crawl crawl.build
fi
