#! /bin/bash

GIT_URL=https://github.com/crawl/crawl.git
SOURCE_DIR=current
LOCK="$PWD/.crawl-fetch.lock"

set -e

if ! mkdir $LOCK 2>/dev/null; then
    echo >&2 "Unable to lock $LOCK, exiting."
    exit 1
fi

cleanup_lock() {
    rmdir $LOCK
}

trap cleanup_lock EXIT

if [[ ! -d "$SOURCE_DIR" ]]; then
    git clone $GIT_URL $SOURCE_DIR
fi

cd $SOURCE_DIR
git pull
git submodule update --init

cd crawl-ref
# ctags incantations courtesy |amethyst
ctags -R \
    --langdef=crawlmap \
    --langmap=crawlmap:+.des \
    --regex-crawlmap='/^ *NAME: *([^ ]*)/\1/q,map,map definition/' \
    --regex-c++='/^ *DEF_BITFIELD *\( *([a-zA-Z0-9_:]*)/\1/t/' \
    --regex-c++='/^ *\{ *\/\/ Book of (.*)/\1/t/i' \
    --regex-c++='/^ *\{ *\/\/ (.*)/\1/t/i' \
    -I decltype+ \
    --extra=+q \
    --exclude=contrib \
    --exclude=android-project \
    --exclude=saves \
    --exclude='tiledef-*' \
    *

# And compile the binary for playable:*
cd source
make clean && make -j5 HURRY=y

if [[ -f crawl ]]; then
    mv crawl crawl.build
fi
